# Generated by Django 5.1.6 on 2025-02-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_alter_category_name_alter_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('It equipment', 'It equipment'), ('phone', 'phone')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('It equipment', 'It equipment'), ('phone', 'phone')], max_length=50, null=True),
        ),
    ]
