# Generated by Django 5.1.6 on 2025-02-23 12:33

# import django.db.models.deletion
# import django.utils.timezone
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('stockmgmt', '0008_alter_category_name'),
#     ]

#     operations = [
#         migrations.RemoveField(
#             model_name='stock',
#             name='export_to_csv',
#         ),
#         migrations.AlterField(
#             model_name='category',
#             name='name',
#             field=models.CharField(max_length=50, unique=True),
#         ),
#         migrations.AlterField(
#             model_name='stock',
#             name='category',
#             field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category'),
#             preserve_default=False,
#         ),
#     ]
# Generated by Django 5.1.6 on 2025-02-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0008_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='export_to_csv',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.category'),
        ),
    ]
