# Generated by Django 5.1.6 on 2025-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0010_stock_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
