# Generated by Django 5.1.6 on 2025-02-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0012_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
