# Generated by Django 5.1.6 on 2025-02-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0013_remove_stock_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_id',
        ),
    ]
