# Generated by Django 5.1.6 on 2025-03-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0014_rename_name_category_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('asset_owner_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=100)),
                ('laptop_bag_issued_date', models.DateField(blank=True, null=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_description', models.TextField(blank=True, null=True)),
                ('po_number', models.CharField(max_length=100)),
                ('sap_code', models.CharField(max_length=100)),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('asset_age', models.IntegerField(help_text='Age in years')),
                ('asset_age_as_on', models.DateField()),
                ('asset_status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], max_length=50)),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('host_name', models.CharField(max_length=100)),
                ('operational_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=100)),
                ('operational_remark', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('assigned_to_user', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=100)),
                ('user_dept', models.CharField(max_length=100)),
                ('user_location', models.CharField(max_length=255)),
                ('placement', models.CharField(max_length=255)),
                ('os_name', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('office_version', models.CharField(max_length=100)),
                ('av', models.BooleanField(default=False)),
                ('dlp', models.BooleanField(default=False)),
                ('pgp', models.BooleanField(default=False)),
                ('bigfix', models.BooleanField(default=False)),
                ('ram_size', models.IntegerField(help_text='Size in GB')),
                ('engineer_name', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DTLTOTNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_name', models.CharField(max_length=255)),
                ('network_id', models.CharField(max_length=50, unique=True)),
                ('ip_range', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DTLTRetired',
            fields=[
                ('serial_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dtlt', models.CharField(max_length=255)),
                ('retired_date', models.DateField()),
                ('reason_for_retirement', models.TextField()),
                ('retired_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('location_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('serial_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('asset_status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], max_length=50)),
                ('created_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAMDetails',
            fields=[
                ('ram_type', models.CharField(max_length=255)),
                ('ram_size', models.IntegerField(help_text='Size in GB')),
                ('serial_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=255)),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('asset_status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], max_length=50)),
                ('created_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('serial_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(help_text='Capacity in GB')),
                ('manufacturer', models.CharField(max_length=255)),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('asset_status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], max_length=50)),
                ('created_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VCProjectorsTV',
            fields=[
                ('serial_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('asset_status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], max_length=50)),
                ('created_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
