# Generated by Django 5.1.6 on 2025-03-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0015_dtlt_dtltotnetwork_dtltretired_locationmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='av',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=50),
        ),
    ]
