# Generated by Django 5.1.6 on 2025-03-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0017_alter_dtlt_bigfix_alter_dtlt_dlp_alter_dtlt_pgp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='av',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='bigfix',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='dlp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='pgp',
            field=models.BooleanField(default=False),
        ),
    ]
