# Generated by Django 5.1.6 on 2025-03-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0018_alter_dtlt_av_alter_dtlt_bigfix_alter_dtlt_dlp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='av',
            field=models.BooleanField(default=False),
        ),
    ]
