# Generated by Django 5.1.6 on 2025-03-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0021_alter_dtlt_av_alter_dtlt_bigfix_alter_dtlt_dlp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='av',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='bigfix',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='dlp',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='pgp',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50),
        ),
    ]
