# Generated by Django 5.1.6 on 2025-03-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0023_alter_dtlt_category_alter_dtlt_os_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
