# Generated by Django 5.1.6 on 2025-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0025_alter_dtlt_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtlt',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='asset_status',
            field=models.CharField(choices=[('Warrenty', 'Warrenty'), ('Expired', 'Expired')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='av',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('NA', 'NA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='bigfix',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('NA', 'NA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='dlp',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('NA', 'NA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='operational_status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Stock', 'Stock')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='pgp',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('NA', 'NA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='ram_size',
            field=models.PositiveBigIntegerField(help_text='Size in GB'),
        ),
    ]
