# Generated by Django 5.1.6 on 2025-03-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0026_dtlt_last_updated_alter_dtlt_asset_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='asset_status',
            field=models.CharField(blank=True, choices=[('Warranty', 'Warranty'), ('Expired', 'Expired')], max_length=50),
        ),
    ]
