# Generated by Django 5.1.6 on 2025-03-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0027_alter_dtlt_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='asset_age',
            field=models.IntegerField(),
        ),
    ]
