# Generated by Django 5.1.6 on 2025-03-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0028_alter_dtlt_asset_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtlt',
            old_name='av',
            new_name='Antivirus',
        ),
        migrations.RenameField(
            model_name='dtlt',
            old_name='dlp',
            new_name='DLP',
        ),
        migrations.RenameField(
            model_name='dtlt',
            old_name='pgp',
            new_name='PGP',
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='bigfix',
            field=models.CharField(choices=[('Encryption', 'Encryption'), ('Bitlocker', 'Bitlocker')], max_length=50),
        ),
    ]
