# Generated by Django 5.1.6 on 2025-03-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0030_alter_dtlt_pgp_alter_dtlt_bigfix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
