# Generated by Django 5.1.6 on 2025-03-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0031_alter_dtlt_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='device_type',
            field=models.CharField(choices=[('Desktop', 'DT'), ('Laptop', 'LT'), ('Workshop', 'Ws')], max_length=100),
        ),
    ]
