# Generated by Django 5.1.6 on 2025-03-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0032_alter_dtlt_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='engineer_name',
            field=models.CharField(choices=[('Vivek Naik', 'Vivek Naik'), ('Ajay Rathod', 'Ajay Rathod')], max_length=255),
        ),
    ]
