# Generated by Django 5.1.6 on 2025-03-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0034_dtlt_custom_status_alter_dtlt_pgp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtlt',
            name='custom_status',
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='operational_status',
            field=models.CharField(choices=[('Operational', 'Operational'), ('Stock', 'Stock')], max_length=100),
        ),
    ]
