# Generated by Django 5.1.6 on 2025-03-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0035_remove_dtlt_custom_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='model_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='operational_remark',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='remarks',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
