# Generated by Django 5.1.6 on 2025-03-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0036_alter_dtlt_model_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='model_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='operational_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
