# Generated by Django 5.1.6 on 2025-03-09 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0037_alter_dtlt_model_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtlt',
            name='PGP',
        ),
        migrations.AddField(
            model_name='dtlt',
            name='Encryption',
            field=models.CharField(choices=[('PGP', 'PGP'), ('Bitlocker', 'Bitlocker'), ('NA', 'NA')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
