# Generated by Django 5.1.6 on 2025-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0038_remove_dtlt_pgp_dtlt_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='asset_age_as_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
