# Generated by Django 5.1.6 on 2025-03-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0040_alter_dtlt_assigned_to_user_alter_dtlt_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtlt',
            name='category',
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='asset_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
