# Generated by Django 5.1.6 on 2025-03-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0041_remove_dtlt_category_alter_dtlt_asset_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='warranty_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='warranty_start_date',
            field=models.DateField(null=True),
        ),
    ]
