# Generated by Django 5.1.6 on 2025-03-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0042_alter_dtlt_warranty_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='Encryption',
            field=models.CharField(choices=[('PGP', 'PGP'), ('Bitlocker', 'Bitlocker')], max_length=50),
        ),
    ]
