# Generated by Django 5.1.6 on 2025-03-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0043_alter_dtlt_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='device_type',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Workshop', 'Workshop')], max_length=100),
        ),
    ]
