# Generated by Django 5.1.6 on 2025-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0045_alter_dtlt_warranty_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='Encryption',
            field=models.CharField(choices=[('PGP', 'PGP'), ('Bitlocker', 'Bitlocker'), ('yes', 'yes')], max_length=50),
        ),
    ]
