# Generated by Django 5.1.6 on 2025-03-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0046_alter_dtlt_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramdetails',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ramdetails',
            name='invoiceno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramdetails',
            name='ponumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ramdetails',
            name='vendordetail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
