# Generated by Django 5.1.6 on 2025-03-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0048_remove_ramdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtlt',
            name='Encryption',
            field=models.CharField(choices=[('PGP', 'PGP'), ('Bitlocker', 'Bitlocker')], max_length=50),
        ),
        migrations.AlterField(
            model_name='dtlt',
            name='device_type',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Workshop', 'Workshop')], db_index=True, max_length=100),
        ),
    ]
