# Generated by Django 5.1.6 on 2025-03-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0050_alter_dtlt_os_version_alter_dtlt_ram_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtltretired',
            name='reason_for_retirement',
            field=models.CharField(max_length=255),
        ),
    ]
